name: Auto-merge PR
on: pull_request_target
jobs:
  enable_automerge:
    if: |
      github.event.pull_request.draft == false && (
        github.actor == 'dependabot[bot]'
      )
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Enable automerge
        run: gh pr merge --repo "${{ github.repository }}" --rebase --auto "${{ github.event.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
