name: Binaries
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: cargo build --release --target ${{ matrix.target }}
      - name: Strip binary
        run: |
          mkdir target/artifact
          strip -o "target/artifact/git-nomad_${GITHUB_REF_NAME}_${{ matrix.target}}" "target/${{ matrix.target }}/release/git-nomad"
      - uses: actions/upload-artifact@v4
        with:
          name: git-nomad_${{ matrix.target }}
          path: "target/artifact/*"
          if-no-files-found: error
