name: Dev
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  rust:
    uses: rraval/workflows/.github/workflows/rust_dev.yml@v1

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
