name: Release
on:
  workflow_dispatch:
  push:
    tags:
    - "v*.*.*"
jobs:
  site:
    uses: ./.github/workflows/site.yml

  crates-io:
    uses: ./.github/workflows/crates-io.yml

  binaries:
    uses: ./.github/workflows/binaries.yml

  release:
    needs: binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: src

      - uses: actions/download-artifact@v4
        with:
          pattern: "git-nomad_*"
          path: artifact
          merge-multiple: true

      - name: Changelog entry for tag
        run: |
          sed -n -e '/^## \['"${GITHUB_REF_NAME}"'\]/,/^## /p' src/CHANGELOG.md | \
            sed -e '1d;$d' | tee RELEASE.md

      - uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        with:
          files: "artifact/*"
          body_path: RELEASE.md
