# https://github.com/AlexanderThaller/hstdb/blob/main/.github/workflows/rust_release.yml
# https://github.com/actions-rs/meta/issues/6
name: Release
on:
  release:
    types: [published]

jobs:
  upload-binary:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
          use-cross: true

      - name: Strip and compress binary
        run: |
          strip "target/${{ matrix.target }}/release/git-nomad"
          gzip --force --best "target/${{ matrix.target }}/release/git-nomad"

      - name: Upload asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: git-nomad_${{ github.event.release.tag_name }}_${{ matrix.target }}.gz
          asset_path: target/${{ matrix.target }}/release/git-nomad.gz
          upload_url: ${{ github.event.release.upload_url }}
          asset_content_type: application/gzip

  cargo-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cargo login "$CRATES_IO_TOKEN"
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      - run: cargo publish
